# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xulpymoney/ui/frmAuxiliarTables.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmAuxiliarTables(object):
    def setupUi(self, frmAuxiliarTables):
        frmAuxiliarTables.setObjectName("frmAuxiliarTables")
        frmAuxiliarTables.resize(612, 541)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmAuxiliarTables.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(frmAuxiliarTables)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(frmAuxiliarTables)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(frmAuxiliarTables)
        self.tabWidget.setObjectName("tabWidget")
        self.tabConceptos = QtWidgets.QWidget()
        self.tabConceptos.setObjectName("tabConceptos")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabConceptos)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mqtwConcepts = mqtwObjects(self.tabConceptos)
        self.mqtwConcepts.setObjectName("mqtwConcepts")
        self.verticalLayout_2.addWidget(self.mqtwConcepts)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tabConceptos, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.actionExpensesAdd = QtWidgets.QAction(frmAuxiliarTables)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/xulpymoney/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExpensesAdd.setIcon(icon1)
        self.actionExpensesAdd.setObjectName("actionExpensesAdd")
        self.actionConceptDelete = QtWidgets.QAction(frmAuxiliarTables)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/xulpymoney/eventdelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConceptDelete.setIcon(icon2)
        self.actionConceptDelete.setObjectName("actionConceptDelete")
        self.actionIncomesAdd = QtWidgets.QAction(frmAuxiliarTables)
        self.actionIncomesAdd.setIcon(icon1)
        self.actionIncomesAdd.setObjectName("actionIncomesAdd")
        self.actionChangeName = QtWidgets.QAction(frmAuxiliarTables)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/xulpymoney/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChangeName.setIcon(icon3)
        self.actionChangeName.setObjectName("actionChangeName")

        self.retranslateUi(frmAuxiliarTables)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmAuxiliarTables)

    def retranslateUi(self, frmAuxiliarTables):
        _translate = QtCore.QCoreApplication.translate
        frmAuxiliarTables.setWindowTitle(_translate("frmAuxiliarTables", "Auxiliar tables"))
        self.label.setText(_translate("frmAuxiliarTables", "Auxiliar tables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConceptos), _translate("frmAuxiliarTables", "Xulpymoney concepts"))
        self.actionExpensesAdd.setText(_translate("frmAuxiliarTables", "Add a expense concept"))
        self.actionExpensesAdd.setToolTip(_translate("frmAuxiliarTables", "Add a expense concept"))
        self.actionConceptDelete.setText(_translate("frmAuxiliarTables", "Delete concept"))
        self.actionConceptDelete.setToolTip(_translate("frmAuxiliarTables", "Delete concept"))
        self.actionIncomesAdd.setText(_translate("frmAuxiliarTables", "Add an income concept"))
        self.actionIncomesAdd.setToolTip(_translate("frmAuxiliarTables", "Add an income concept"))
        self.actionChangeName.setText(_translate("frmAuxiliarTables", "Change name"))
        self.actionChangeName.setToolTip(_translate("frmAuxiliarTables", "Change name"))
from xulpymoney.ui.myqtablewidget import mqtwObjects
import xulpymoney.images.xulpymoney_rc
