# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xulpymoney/ui/frmHlContractAdd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmHlContractAddui(object):
    def setupUi(self, frmHlContractAddui):
        frmHlContractAddui.setObjectName("frmHlContractAddui")
        frmHlContractAddui.setWindowModality(QtCore.Qt.WindowModal)
        frmHlContractAddui.resize(566, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/dividends.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmHlContractAddui.setWindowIcon(icon)
        frmHlContractAddui.setModal(True)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(frmHlContractAddui)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(frmHlContractAddui)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("color: rgb(0, 128, 0);")
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.wdgDT = wdgDatetime(frmHlContractAddui)
        self.wdgDT.setObjectName("wdgDT")
        self.horizontalLayout.addWidget(self.wdgDT)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(frmHlContractAddui)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmb = QtWidgets.QComboBox(frmHlContractAddui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb.sizePolicy().hasHeightForWidth())
        self.cmb.setSizePolicy(sizePolicy)
        self.cmb.setObjectName("cmb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb)
        self.lblGross = QtWidgets.QLabel(frmHlContractAddui)
        self.lblGross.setObjectName("lblGross")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblGross)
        self.txtBruto = myQLineEdit(frmHlContractAddui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBruto.sizePolicy().hasHeightForWidth())
        self.txtBruto.setSizePolicy(sizePolicy)
        self.txtBruto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtBruto.setObjectName("txtBruto")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtBruto)
        self.lblGrossAccount = QtWidgets.QLabel(frmHlContractAddui)
        self.lblGrossAccount.setObjectName("lblGrossAccount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblGrossAccount)
        self.wdgCurrencyConversion = wdgCurrencyConversion(frmHlContractAddui)
        self.wdgCurrencyConversion.setObjectName("wdgCurrencyConversion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wdgCurrencyConversion)
        self.lblLiquido_4 = QtWidgets.QLabel(frmHlContractAddui)
        self.lblLiquido_4.setObjectName("lblLiquido_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblLiquido_4)
        self.txtRetencion = myQLineEdit(frmHlContractAddui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRetencion.sizePolicy().hasHeightForWidth())
        self.txtRetencion.setSizePolicy(sizePolicy)
        self.txtRetencion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtRetencion.setObjectName("txtRetencion")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRetencion)
        self.lblLiquido_5 = QtWidgets.QLabel(frmHlContractAddui)
        self.lblLiquido_5.setObjectName("lblLiquido_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblLiquido_5)
        self.txtDPA = myQLineEdit(frmHlContractAddui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDPA.sizePolicy().hasHeightForWidth())
        self.txtDPA.setSizePolicy(sizePolicy)
        self.txtDPA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtDPA.setObjectName("txtDPA")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtDPA)
        self.lblLiquido = QtWidgets.QLabel(frmHlContractAddui)
        self.lblLiquido.setObjectName("lblLiquido")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblLiquido)
        self.txtComision = myQLineEdit(frmHlContractAddui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtComision.sizePolicy().hasHeightForWidth())
        self.txtComision.setSizePolicy(sizePolicy)
        self.txtComision.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtComision.setObjectName("txtComision")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtComision)
        self.lblLiquido_7 = QtWidgets.QLabel(frmHlContractAddui)
        self.lblLiquido_7.setObjectName("lblLiquido_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblLiquido_7)
        self.txtNeto = myQLineEdit(frmHlContractAddui)
        self.txtNeto.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNeto.sizePolicy().hasHeightForWidth())
        self.txtNeto.setSizePolicy(sizePolicy)
        self.txtNeto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNeto.setReadOnly(True)
        self.txtNeto.setObjectName("txtNeto")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtNeto)
        self.verticalLayout.addLayout(self.formLayout)
        self.lblTPC = QtWidgets.QLabel(frmHlContractAddui)
        self.lblTPC.setText("")
        self.lblTPC.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTPC.setObjectName("lblTPC")
        self.verticalLayout.addWidget(self.lblTPC)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cmd = QtWidgets.QPushButton(frmHlContractAddui)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/xulpymoney/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmd.setIcon(icon1)
        self.cmd.setObjectName("cmd")
        self.horizontalLayout_2.addWidget(self.cmd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(frmHlContractAddui)
        QtCore.QMetaObject.connectSlotsByName(frmHlContractAddui)
        frmHlContractAddui.setTabOrder(self.cmb, self.txtBruto)
        frmHlContractAddui.setTabOrder(self.txtBruto, self.txtRetencion)
        frmHlContractAddui.setTabOrder(self.txtRetencion, self.txtDPA)
        frmHlContractAddui.setTabOrder(self.txtDPA, self.txtComision)
        frmHlContractAddui.setTabOrder(self.txtComision, self.cmd)
        frmHlContractAddui.setTabOrder(self.cmd, self.txtNeto)

    def retranslateUi(self, frmHlContractAddui):
        _translate = QtCore.QCoreApplication.translate
        frmHlContractAddui.setWindowTitle(_translate("frmHlContractAddui", "Daily high-low investment contract"))
        self.lblTitulo.setText(_translate("frmHlContractAddui", "Daily high-low investment contract"))
        self.label.setText(_translate("frmHlContractAddui", "Select dividend type"))
        self.lblGross.setText(_translate("frmHlContractAddui", "Gross amount"))
        self.txtBruto.setText(_translate("frmHlContractAddui", "0"))
        self.lblGrossAccount.setText(_translate("frmHlContractAddui", "Gross amount in account currency"))
        self.lblLiquido_4.setText(_translate("frmHlContractAddui", "Withholding tax amount"))
        self.txtRetencion.setText(_translate("frmHlContractAddui", "0"))
        self.lblLiquido_5.setText(_translate("frmHlContractAddui", "Dividend per share"))
        self.txtDPA.setText(_translate("frmHlContractAddui", "0"))
        self.lblLiquido.setText(_translate("frmHlContractAddui", "Comission"))
        self.txtComision.setText(_translate("frmHlContractAddui", "0"))
        self.lblLiquido_7.setText(_translate("frmHlContractAddui", "Net amount"))
        self.txtNeto.setText(_translate("frmHlContractAddui", "0"))

from xulpymoney.ui.myqlineedit import myQLineEdit
from xulpymoney.ui.wdgCurrencyConversion import wdgCurrencyConversion
from xulpymoney.ui.wdgDatetime import wdgDatetime
import xulpymoney.images.xulpymoney_rc
