# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgOpportunitiesAdd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wdgOpportunitiesAdd(object):
    def setupUi(self, wdgOpportunitiesAdd):
        wdgOpportunitiesAdd.setObjectName("wdgOpportunitiesAdd")
        wdgOpportunitiesAdd.resize(959, 328)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/bank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wdgOpportunitiesAdd.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgOpportunitiesAdd)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(wdgOpportunitiesAdd)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setText("")
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.productSelector = wdgProductSelector(wdgOpportunitiesAdd)
        self.productSelector.setObjectName("productSelector")
        self.verticalLayout.addWidget(self.productSelector)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.deDate = QtWidgets.QDateEdit(wdgOpportunitiesAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deDate.sizePolicy().hasHeightForWidth())
        self.deDate.setSizePolicy(sizePolicy)
        self.deDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deDate.setCalendarPopup(True)
        self.deDate.setObjectName("deDate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deDate)
        self.label_2 = QtWidgets.QLabel(wdgOpportunitiesAdd)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtPrice = myQLineEdit(wdgOpportunitiesAdd)
        self.txtPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPrice.setObjectName("txtPrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPrice)
        self.label_5 = QtWidgets.QLabel(wdgOpportunitiesAdd)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonbox = QtWidgets.QDialogButtonBox(wdgOpportunitiesAdd)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox.setCenterButtons(True)
        self.buttonbox.setObjectName("buttonbox")
        self.verticalLayout.addWidget(self.buttonbox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.actionInvestmentReport = QtWidgets.QAction(wdgOpportunitiesAdd)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/xulpymoney/report2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInvestmentReport.setIcon(icon1)
        self.actionInvestmentReport.setObjectName("actionInvestmentReport")
        self.actionAccountReport = QtWidgets.QAction(wdgOpportunitiesAdd)
        self.actionAccountReport.setIcon(icon1)
        self.actionAccountReport.setObjectName("actionAccountReport")
        self.actionBankAdd = QtWidgets.QAction(wdgOpportunitiesAdd)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/xulpymoney/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBankAdd.setIcon(icon2)
        self.actionBankAdd.setObjectName("actionBankAdd")
        self.actionBankDelete = QtWidgets.QAction(wdgOpportunitiesAdd)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/xulpymoney/button_cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBankDelete.setIcon(icon3)
        self.actionBankDelete.setObjectName("actionBankDelete")
        self.actionBankEdit = QtWidgets.QAction(wdgOpportunitiesAdd)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/xulpymoney/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBankEdit.setIcon(icon4)
        self.actionBankEdit.setObjectName("actionBankEdit")
        self.actionActive = QtWidgets.QAction(wdgOpportunitiesAdd)
        self.actionActive.setCheckable(True)
        self.actionActive.setObjectName("actionActive")

        self.retranslateUi(wdgOpportunitiesAdd)
        QtCore.QMetaObject.connectSlotsByName(wdgOpportunitiesAdd)

    def retranslateUi(self, wdgOpportunitiesAdd):
        _translate = QtCore.QCoreApplication.translate
        self.deDate.setDisplayFormat(_translate("wdgOpportunitiesAdd", "yyyy/MM/dd"))
        self.label_2.setText(_translate("wdgOpportunitiesAdd", "Opportunity date"))
        self.txtPrice.setText(_translate("wdgOpportunitiesAdd", "0"))
        self.label_5.setText(_translate("wdgOpportunitiesAdd", "Price"))
        self.actionInvestmentReport.setText(_translate("wdgOpportunitiesAdd", "Investment report"))
        self.actionInvestmentReport.setToolTip(_translate("wdgOpportunitiesAdd", "Investment report"))
        self.actionAccountReport.setText(_translate("wdgOpportunitiesAdd", "Account report"))
        self.actionAccountReport.setToolTip(_translate("wdgOpportunitiesAdd", "Account report"))
        self.actionBankAdd.setText(_translate("wdgOpportunitiesAdd", "New bank"))
        self.actionBankAdd.setToolTip(_translate("wdgOpportunitiesAdd", "New bank"))
        self.actionBankDelete.setText(_translate("wdgOpportunitiesAdd", "Delete bank"))
        self.actionBankDelete.setToolTip(_translate("wdgOpportunitiesAdd", "Delete bank"))
        self.actionBankEdit.setText(_translate("wdgOpportunitiesAdd", "Edit bank"))
        self.actionBankEdit.setToolTip(_translate("wdgOpportunitiesAdd", "Edit bank"))
        self.actionActive.setText(_translate("wdgOpportunitiesAdd", "Is it active?"))
        self.actionActive.setToolTip(_translate("wdgOpportunitiesAdd", "Is it active?"))

from myqlineedit import myQLineEdit
from wdgProductSelector import wdgProductSelector
import xulpymoney_rc
