# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xulpymoney/ui/wdgDerivativesReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgDerivativesReport(object):
    def setupUi(self, wdgDerivativesReport):
        wdgDerivativesReport.setObjectName("wdgDerivativesReport")
        wdgDerivativesReport.setProperty("modal", False)
        wdgDerivativesReport.resize(981, 781)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(wdgDerivativesReport)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(wdgDerivativesReport)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.wyData = wdgYear(wdgDerivativesReport)
        self.wyData.setObjectName("wyData")
        self.horizontalLayout.addWidget(self.wyData)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tab = QtWidgets.QTabWidget(wdgDerivativesReport)
        self.tab.setTabsClosable(True)
        self.tab.setObjectName("tab")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mqtwTotal = mqtw(self.tab_4)
        self.mqtwTotal.setObjectName("mqtwTotal")
        self.verticalLayout_3.addWidget(self.mqtwTotal)
        self.tab.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wdgIOHSLong = wdgInvestmentOperationHistoricalSelector(self.tab_2)
        self.wdgIOHSLong.setObjectName("wdgIOHSLong")
        self.verticalLayout_2.addWidget(self.wdgIOHSLong)
        self.wdgIOHSShort = wdgInvestmentOperationHistoricalSelector(self.tab_2)
        self.wdgIOHSShort.setObjectName("wdgIOHSShort")
        self.verticalLayout_2.addWidget(self.wdgIOHSShort)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tab.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.actionShowAdjustments = QtWidgets.QAction(wdgDerivativesReport)
        self.actionShowAdjustments.setObjectName("actionShowAdjustments")

        self.retranslateUi(wdgDerivativesReport)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgDerivativesReport)

    def retranslateUi(self, wdgDerivativesReport):
        _translate = QtCore.QCoreApplication.translate
        self.lbl.setText(_translate("wdgDerivativesReport", "Derivatives report"))
        self.tab.setTabText(self.tab.indexOf(self.tab_4), _translate("wdgDerivativesReport", "Historical evolution"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("wdgDerivativesReport", "Old"))
        self.actionShowAdjustments.setText(_translate("wdgDerivativesReport", "Show adjustments"))
        self.actionShowAdjustments.setToolTip(_translate("wdgDerivativesReport", "Show adjustments"))
from xulpymoney.ui.myqtablewidget import mqtw
from xulpymoney.ui.wdgInvestmentOperationsSelector import wdgInvestmentOperationHistoricalSelector
from xulpymoney.ui.wdgYear import wdgYear
import xulpymoney.images.xulpymoney_rc
