# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgQuotesUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wdgQuotesUpdate(object):
    def setupUi(self, wdgQuotesUpdate):
        wdgQuotesUpdate.setObjectName("wdgQuotesUpdate")
        wdgQuotesUpdate.resize(740, 468)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(wdgQuotesUpdate)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(wdgQuotesUpdate)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.chkUserOnly = QtWidgets.QCheckBox(wdgQuotesUpdate)
        self.chkUserOnly.setChecked(True)
        self.chkUserOnly.setObjectName("chkUserOnly")
        self.verticalLayout.addWidget(self.chkUserOnly)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(wdgQuotesUpdate)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 341, 292))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layIntraday = QtWidgets.QGridLayout()
        self.layIntraday.setObjectName("layIntraday")
        self.wyahoo = wdgSource(self.scrollAreaWidgetContents)
        self.wyahoo.setObjectName("wyahoo")
        self.layIntraday.addWidget(self.wyahoo, 0, 0, 1, 1)
        self.wmc = wdgSource(self.scrollAreaWidgetContents)
        self.wmc.setObjectName("wmc")
        self.layIntraday.addWidget(self.wmc, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.layIntraday)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.cmdIntraday = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdIntraday.setIcon(icon)
        self.cmdIntraday.setObjectName("cmdIntraday")
        self.verticalLayout_2.addWidget(self.cmdIntraday)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(wdgQuotesUpdate)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 341, 292))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layDaily = QtWidgets.QVBoxLayout()
        self.layDaily.setObjectName("layDaily")
        self.wyahoohistorical = wdgSource(self.scrollAreaWidgetContents_2)
        self.wyahoohistorical.setObjectName("wyahoohistorical")
        self.layDaily.addWidget(self.wyahoohistorical)
        self.wmorningstar = wdgSource(self.scrollAreaWidgetContents_2)
        self.wmorningstar.setObjectName("wmorningstar")
        self.layDaily.addWidget(self.wmorningstar)
        self.verticalLayout_3.addLayout(self.layDaily)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.cmdDaily = QtWidgets.QPushButton(self.groupBox_2)
        self.cmdDaily.setIcon(icon)
        self.cmdDaily.setObjectName("cmdDaily")
        self.verticalLayout_4.addWidget(self.cmdDaily)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(248, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cmdAll = QtWidgets.QPushButton(wdgQuotesUpdate)
        self.cmdAll.setIcon(icon)
        self.cmdAll.setObjectName("cmdAll")
        self.horizontalLayout_2.addWidget(self.cmdAll)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(wdgQuotesUpdate)
        QtCore.QMetaObject.connectSlotsByName(wdgQuotesUpdate)

    def retranslateUi(self, wdgQuotesUpdate):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("wdgQuotesUpdate", "Auxiliar tables"))
        self.chkUserOnly.setToolTip(_translate("wdgQuotesUpdate", "If it\'s unchecked, Xulpymoney will update all products marked as autoupdate"))
        self.chkUserOnly.setText(_translate("wdgQuotesUpdate", "Update only investments of the user"))
        self.groupBox.setTitle(_translate("wdgQuotesUpdate", "Intraday sources"))
        self.cmdIntraday.setText(_translate("wdgQuotesUpdate", "Update all intraday sources"))
        self.groupBox_2.setTitle(_translate("wdgQuotesUpdate", "Daily sources"))
        self.cmdDaily.setText(_translate("wdgQuotesUpdate", "Update all daily sources"))
        self.cmdAll.setText(_translate("wdgQuotesUpdate", "Update all sources"))

from libsources import wdgSource
import xulpymoney_rc
