# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xulpymoney/ui/wdgInvestmentsRanking.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgInvestmentsRanking(object):
    def setupUi(self, wdgInvestmentsRanking):
        wdgInvestmentsRanking.setObjectName("wdgInvestmentsRanking")
        wdgInvestmentsRanking.resize(750, 524)
        self.horizontalLayout = QtWidgets.QHBoxLayout(wdgInvestmentsRanking)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(wdgInvestmentsRanking)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.groupBox = QtWidgets.QGroupBox(wdgInvestmentsRanking)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radYear = QtWidgets.QRadioButton(self.groupBox)
        self.radYear.setObjectName("radYear")
        self.horizontalLayout_4.addWidget(self.radYear)
        self.wy = wdgYear(self.groupBox)
        self.wy.setObjectName("wy")
        self.horizontalLayout_4.addWidget(self.wy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radAll = QtWidgets.QRadioButton(self.groupBox)
        self.radAll.setChecked(True)
        self.radAll.setObjectName("radAll")
        self.horizontalLayout_5.addWidget(self.radAll)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.tab = QtWidgets.QTabWidget(wdgInvestmentsRanking)
        self.tab.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tab.setObjectName("tab")
        self.tab_ = QtWidgets.QWidget()
        self.tab_.setObjectName("tab_")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tblCurrentOperations = myQTableWidget(self.tab_)
        self.tblCurrentOperations.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblCurrentOperations.setAlternatingRowColors(True)
        self.tblCurrentOperations.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblCurrentOperations.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblCurrentOperations.setObjectName("tblCurrentOperations")
        self.tblCurrentOperations.setColumnCount(0)
        self.tblCurrentOperations.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tblCurrentOperations)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/crown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab.addTab(self.tab_, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblOperations = myQTableWidget(self.tab_2)
        self.tblOperations.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblOperations.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblOperations.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblOperations.setObjectName("tblOperations")
        self.tblOperations.setColumnCount(0)
        self.tblOperations.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tblOperations)
        self.tab.addTab(self.tab_2, icon, "")
        self.verticalLayout.addWidget(self.tab)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.actionSameProduct = QtWidgets.QAction(wdgInvestmentsRanking)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/xulpymoney/bundle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSameProduct.setIcon(icon1)
        self.actionSameProduct.setObjectName("actionSameProduct")
        self.actionSameProductFIFO = QtWidgets.QAction(wdgInvestmentsRanking)
        self.actionSameProductFIFO.setIcon(icon1)
        self.actionSameProductFIFO.setObjectName("actionSameProductFIFO")
        self.actionProduct = QtWidgets.QAction(wdgInvestmentsRanking)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/xulpymoney/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProduct.setIcon(icon2)
        self.actionProduct.setObjectName("actionProduct")

        self.retranslateUi(wdgInvestmentsRanking)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgInvestmentsRanking)

    def retranslateUi(self, wdgInvestmentsRanking):
        _translate = QtCore.QCoreApplication.translate
        self.lbl.setText(_translate("wdgInvestmentsRanking", "Investments ranking"))
        self.groupBox.setTitle(_translate("wdgInvestmentsRanking", "Options"))
        self.radYear.setText(_translate("wdgInvestmentsRanking", "Evaluate investment operations from selected year"))
        self.radAll.setText(_translate("wdgInvestmentsRanking", "Evaluate all investments"))
        self.tab.setTabText(self.tab.indexOf(self.tab_), _translate("wdgInvestmentsRanking", "Merging current operations of the same product"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("wdgInvestmentsRanking", "Merging all operations of the same product"))
        self.actionSameProduct.setText(_translate("wdgInvestmentsRanking", "Same product Investments merging current operations"))
        self.actionSameProduct.setToolTip(_translate("wdgInvestmentsRanking", "Same product Investments merging current operations"))
        self.actionSameProductFIFO.setText(_translate("wdgInvestmentsRanking", "Same product Investments merging operations"))
        self.actionSameProductFIFO.setToolTip(_translate("wdgInvestmentsRanking", "Same product Investments merging operations"))
        self.actionProduct.setText(_translate("wdgInvestmentsRanking", "Product report"))
        self.actionProduct.setToolTip(_translate("wdgInvestmentsRanking", "Product report"))
from xulpymoney.ui.myqtablewidget import myQTableWidget
from xulpymoney.ui.wdgYear import wdgYear
import xulpymoney.images.xulpymoney_rc
