# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xulpymoney/ui/wdgStrategyResults.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgStrategyResults(object):
    def setupUi(self, wdgStrategyResults):
        wdgStrategyResults.setObjectName("wdgStrategyResults")
        wdgStrategyResults.resize(1048, 499)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(wdgStrategyResults)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(wdgStrategyResults)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lblPixmap = QtWidgets.QLabel(wdgStrategyResults)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPixmap.sizePolicy().hasHeightForWidth())
        self.lblPixmap.setSizePolicy(sizePolicy)
        self.lblPixmap.setMinimumSize(QtCore.QSize(48, 48))
        self.lblPixmap.setMaximumSize(QtCore.QSize(48, 48))
        self.lblPixmap.setPixmap(QtGui.QPixmap(":/xulpymoney/tools-wizard.png"))
        self.lblPixmap.setScaledContents(True)
        self.lblPixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPixmap.setObjectName("lblPixmap")
        self.horizontalLayout_4.addWidget(self.lblPixmap)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(wdgStrategyResults)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.cmbStrategies = QtWidgets.QComboBox(wdgStrategyResults)
        self.cmbStrategies.setObjectName("cmbStrategies")
        self.horizontalLayout_5.addWidget(self.cmbStrategies)
        self.cmdStrategyAdd = QtWidgets.QToolButton(wdgStrategyResults)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/xulpymoney/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdStrategyAdd.setIcon(icon)
        self.cmdStrategyAdd.setObjectName("cmdStrategyAdd")
        self.horizontalLayout_5.addWidget(self.cmdStrategyAdd)
        self.cmdStrategyEdit = QtWidgets.QToolButton(wdgStrategyResults)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/xulpymoney/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdStrategyEdit.setIcon(icon1)
        self.cmdStrategyEdit.setObjectName("cmdStrategyEdit")
        self.horizontalLayout_5.addWidget(self.cmdStrategyEdit)
        self.cmdStrategyDelete = QtWidgets.QToolButton(wdgStrategyResults)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/xulpymoney/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdStrategyDelete.setIcon(icon2)
        self.cmdStrategyDelete.setObjectName("cmdStrategyDelete")
        self.horizontalLayout_5.addWidget(self.cmdStrategyDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(wdgStrategyResults)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wdgDtFrom = wdgDatetime(self.groupBox)
        self.wdgDtFrom.setObjectName("wdgDtFrom")
        self.verticalLayout_2.addWidget(self.wdgDtFrom)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(wdgStrategyResults)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wdgDtTo = wdgDatetime(self.groupBox_2)
        self.wdgDtTo.setObjectName("wdgDtTo")
        self.horizontalLayout.addWidget(self.wdgDtTo)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cmsInvestments = cmbManagerSelector(wdgStrategyResults)
        self.cmsInvestments.setObjectName("cmsInvestments")
        self.verticalLayout.addWidget(self.cmsInvestments)
        self.tab_4 = QtWidgets.QTabWidget(wdgStrategyResults)
        self.tab_4.setObjectName("tab_4")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mqtwCurrent = QtWidgets.QWidget(self.tab)
        self.mqtwCurrent.setObjectName("mqtwCurrent")
        self.horizontalLayout_3.addWidget(self.mqtwCurrent)
        self.tab_4.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mqtwHistorical = QtWidgets.QWidget(self.tab_2)
        self.mqtwHistorical.setObjectName("mqtwHistorical")
        self.horizontalLayout_6.addWidget(self.mqtwHistorical)
        self.tab_4.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mqtwDividends = QtWidgets.QWidget(self.tab_3)
        self.mqtwDividends.setObjectName("mqtwDividends")
        self.horizontalLayout_7.addWidget(self.mqtwDividends)
        self.tab_4.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tab_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(wdgStrategyResults)
        self.tab_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(wdgStrategyResults)

    def retranslateUi(self, wdgStrategyResults):
        _translate = QtCore.QCoreApplication.translate
        wdgStrategyResults.setWindowTitle(_translate("wdgStrategyResults", "Form"))
        self.lblTitulo.setText(_translate("wdgStrategyResults", "Strategy results"))
        self.label.setText(_translate("wdgStrategyResults", "Select your strategy results"))
        self.cmdStrategyAdd.setText(_translate("wdgStrategyResults", "..."))
        self.cmdStrategyEdit.setText(_translate("wdgStrategyResults", "..."))
        self.cmdStrategyDelete.setText(_translate("wdgStrategyResults", "..."))
        self.groupBox.setTitle(_translate("wdgStrategyResults", "From"))
        self.groupBox_2.setTitle(_translate("wdgStrategyResults", "To"))
        self.tab_4.setTabText(self.tab_4.indexOf(self.tab), _translate("wdgStrategyResults", "Current operations"))
        self.tab_4.setTabText(self.tab_4.indexOf(self.tab_2), _translate("wdgStrategyResults", "Historical Operations"))
        self.tab_4.setTabText(self.tab_4.indexOf(self.tab_3), _translate("wdgStrategyResults", "Dividends"))
from xulpymoney.ui.frmSelector import cmbManagerSelector
from xulpymoney.ui.wdgDatetime import wdgDatetime
import xulpymoney.images.xulpymoney_rc
