# -*- coding: UTF-8 -*-
from mod_python import util
from core import *
from xul import *
from translate import  _

def index(req):   
    f=os.popen("/usr/bin/uname -s -r -p")
    so=f.read()
    f.close()
    
    f=os.popen("/usr/bin/python -V 2>&1")
    py=f.read()
    f.close()
    
    f=os.popen("/usr/bin/firefox -v 2>&1")
    xu=f.read()
    f.close()
    
    f=os.popen("/usr/bin/postgres --version")
    po=f.read()
    f.close()
    req.content_type="application/vnd.mozilla.xul+xml"
    req.write(xulheaderwindowmenu(_("Acerca de Xulpymoney")))    
    req.write('<vbox  flex="5">')
    req.write('<label id="titulo" value="'+_('Acerca de Xulpymoney')+'" />')
    req.write('        <label value="'+str(version)+'" style="text-align : center;"/>')
    
    req.write('        <spacer flex="1"/>')
    req.write('        <hbox flex="4">')
    req.write('        <spacer flex="5"/>')
    req.write('        <tabbox orient="vertical" flex="1">')
    req.write('        <tabs>')
    req.write('        <tab label="'+_('Curiosidades')+'" />')
    req.write('        <tab label="'+_('Autores             ')+'" />')
    req.write('        <tab label="'+_('Tecnología utilizada')+'" />')
    req.write('        <tab label="'+_('Licencia de programa')+'" />')
    req.write('        </tabs>')
    req.write('        <tabpanels flex="1">')
    req.write('        <vbox>')
    req.write('            <grid pack="center">')
    req.write('                <columns>')
    req.write('                    <column flex="1" />')
    req.write('                    <column flex="1" />')
    req.write('                    <column flex="1" />')
    req.write('                </columns>')
    req.write('                <rows>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Operación de bolsa de mayor importe:')+'"/>')
    req.write('                        <label value="Fecha" />')
    req.write('                        <label value="Valor" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Primera operación de usuario:')+'"/>')
    req.write('                        <label value="Mariano Muñoz" />')
    req.write('                        <label value="turulomio@yahoo.es" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Mayor saldo:')+'"/>')
    req.write('                        <label value="Mariano Muñoz" />')
    req.write('                        <label value="turulomio@yahoo.es" />')
    req.write('                    </row>')
    req.write('                </rows>')
    req.write('            </grid>')
    req.write('        </vbox>')
    req.write('        <vbox>')
    req.write('            <grid pack="center">')
    req.write('                <columns>')
    req.write('                    <column flex="1" />')
    req.write('                    <column flex="1" />')
    req.write('                    <column flex="1" />')
    req.write('                </columns>')
    req.write('                <rows>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Idea:')+'"/>')
    req.write('                        <label value="Mariano Muñoz" />')
    req.write('                        <label value="turulomio@yahoo.es" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Desarrollo:')+'"/>')
    req.write('                        <label value="Mariano Muñoz" />')
    req.write('                        <label value="turulomio@yahoo.es" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Traducción:')+'"/>')
    req.write('                        <label value="Mariano Muñoz" />')
    req.write('                        <label value="turulomio@yahoo.es" />')
    req.write('                    </row>')
    req.write('                </rows>')
    req.write('            </grid>')
    req.write('        </vbox>')
    req.write('        <vbox>')
    req.write('            <grid pack="center">')
    req.write('                <columns>º')
    req.write('                    <column flex="1" />')
    req.write('                    <column flex="1" />')
    req.write('                </columns>')
    req.write('                <rows>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Sistema Operativo:')+'"/>')
    req.write('                        <label value="'+so+'" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="Python:"/>')
    req.write('                        <label value="'+py+'" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="Mozilla Firefox (XUL):"/>')
    req.write('                        <label value="'+xu+'" />')
    req.write('                    </row>')
    req.write('                    <row>')
    req.write('                        <label id="negrita" value="'+_('Base de datos:')+'"/>')
    req.write('                        <label value="'+po+'" />')
    req.write('                    </row>')
    req.write('                </rows>')
    req.write('            </grid>')
    req.write('        </vbox>')
    req.write('        <vbox>')
    req.write('            <iframe  src="GPL-3.txt" flex="6"/>')
    req.write('        </vbox>')
    req.write('        </tabpanels>')
    req.write('        </tabbox>')
    
    req.write('        <spacer flex="5"/>')
    req.write('        </hbox>')
    
    req.write('        </vbox>')
    req.write(xulfoot())


