@ECHO ON
call c:\Python34\Lib\site-packages\PyQt5\pyrcc5.exe  images/xulpymoney.qrc -o images/xulpymoney_rc.py  &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmAbout.ui -o ui/Ui_frmAbout.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmAccess.ui -o ui/Ui_frmAccess.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmDPSAdd.ui -o ui/Ui_frmDPSAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmHelp.ui -o ui/Ui_frmHelp.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmInit.ui -o ui/Ui_frmInit.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmMain.ui -o ui/Ui_frmMain.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmSplit.ui -o ui/Ui_frmSplit.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmAccountOperationsAdd.ui -o ui/Ui_frmAccountOperationsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmAuxiliarTables.ui -o ui/Ui_frmAuxiliarTables.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgBanks.ui -o ui/Ui_wdgBanks.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgCalculator.ui -o ui/Ui_wdgCalculator.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgConcepts.ui -o ui/Ui_wdgConcepts.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgConceptsHistorical.ui -o ui/Ui_wdgConceptsHistorical.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgAccounts.ui -o ui/Ui_wdgAccounts.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgDisReinvest.ui -o ui/Ui_wdgDisReinvest.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmAccountsReport.ui -o ui/Ui_frmAccountsReport.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgInvestmentClasses.ui -o ui/Ui_wdgInvestmentClasses.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgDividendsReport.ui -o ui/Ui_wdgDividendsReport.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgAPR.ui -o ui/Ui_wdgAPR.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgIndexRange.ui -o ui/Ui_wdgIndexRange.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgInvestments.ui -o ui/Ui_wdgInvestments.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgLastCurrent.ui -o ui/Ui_wdgLastCurrent.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgOrders.ui -o ui/Ui_wdgOrders.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgOrdersAdd.ui -o ui/Ui_wdgOrdersAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmDividendsAdd.ui -o ui/Ui_frmDividendsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmInvestmentReport.ui -o ui/Ui_frmInvestmentReport.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmInvestmentOperationsAdd.ui -o ui/Ui_frmInvestmentOperationsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmSellingPoint.ui -o ui/Ui_frmSellingPoint.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmSettings.ui -o ui/Ui_frmSettings.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmCreditCardsAdd.ui -o ui/Ui_frmCreditCardsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmTransfer.ui -o ui/Ui_frmTransfer.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmSharesTransfer.ui -o ui/Ui_frmSharesTransfer.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgTotal.ui -o ui/Ui_wdgTotal.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmProductReport.ui -o ui/Ui_frmProductReport.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmQuotesIBM.ui -o ui/Ui_frmQuotesIBM.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmSelector.ui -o ui/Ui_frmSelector.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/frmEstimationsAdd.ui -o ui/Ui_frmEstimationsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgDatetime.ui -o ui/Ui_wdgDatetime.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgProducts.ui -o ui/Ui_wdgProducts.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgQuotesUpdate.ui -o ui/Ui_wdgQuotesUpdate.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgSimulations.ui -o ui/Ui_wdgSimulations.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgSimulationsAdd.ui -o ui/Ui_wdgSimulationsAdd.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgSource.ui -o ui/Ui_wdgSource.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgInvestmentsOperations.ui -o ui/Ui_wdgInvestmentsOperations.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgMergeCodes.ui -o ui/Ui_wdgMergeCodes.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgYearMonth.ui -o ui/Ui_wdgYearMonth.py &
call c:\Python34\Lib\site-packages\PyQt5\pyuic5.bat ui/wdgYear.ui -o ui/Ui_wdgYear.py &

call c:\Python34\Lib\site-packages\PyQt5\pylupdate5.exe -noobsolete -verbose  xulpymoney.pro
call c:\Python34\Lib\site-packages\PyQt5\lrelease.exe xulpymoney.pro
