#!/usr/bin/python    
# -*- coding: utf-8 -*-  
import os, adodb, datetime, sys
sys.path.append("/etc/xulpymoney")
sys.path.append("/usr/lib/xulpymoney")
import config

from inversion_actualizacion import *

if check_internet_html()==False:
    print (str(datetime.datetime.now()) + " " + "No se puede actualizar porque no hay Internet")
    sys.exit(255)



cwd=os.getcwd()

con = adodb.NewADOConnection("postgres")
con.Connect(config.host,config.user,config.password, config.dbname)

# BORRA LA BASE DE DATOS
con.Execute("delete from ibex35")

# SE DESCARGA UNA NUEVA
print "* Descargando fichero..."
os.system ("wget 'http://ichart.yahoo.com/table.csv?s=%5EIBEX&a=0&b=1&c=1995&d=" + str(datetime.date.today().month-1) + "&e=" + str(datetime.date.today().day) + "&f="+ str(datetime.date.today().year) + "&g=d&ignore=.csv' -O /tmp/ibex35.csv &> /dev/null")

# INSERTA LA NUEVA
print "* Procesando el fichero..."
f=open("/tmp/ibex35.csv","r")
f.readline()
arr=[]
for line in f:
	arrline=line.split(",")
	arr.append((arrline[0], float(arrline[4]), 0.0))
f.close()


n=len(arr)-1

#genera un fichero fecha;cierre;diff
f=open("/tmp/ibex35.mod.csv","w")
#necesita un primer registro para calcular la diferencia
s= arr[n][0] + ";" + str(arr[n][1]) + ";"+ str(arr[n][2])+ "\n"
#genera un fichero fecha;cierre;diff
for i in range(0,n):
	arr[n-1-i]=(arr[n-1-i][0], arr[n-1-i][1], arr[n-1-i][1]-arr[n-i][1])
	s=s + arr[n-1-i][0] + ";" + str(arr[n-1-i][1]) + ";"+ str(arr[n-1-i][2])+ "\n"
f.write(s)
f.close()
os.system("chmod 666 /tmp/ibex35.mod.csv")
con.Execute("COPY ibex35 FROM '/tmp/ibex35.mod.csv' USING DELIMITERS ';';")
con.Close()
print "  - Se han añadido", len (arr), "registros"
