from PyQt5.QtCore import QT_TRANSLATE_NOOP
## To translate this strings you must use qApp.translate('Mem',string) o mem.trHS.
QT_TRANSLATE_NOOP('Mem','Personal Management')
QT_TRANSLATE_NOOP('Mem','Cash')
QT_TRANSLATE_NOOP('Mem', 'Desconocido')
QT_TRANSLATE_NOOP('Mem', 'Initiating bank account')
QT_TRANSLATE_NOOP('Mem', 'Supermarket')
QT_TRANSLATE_NOOP('Mem', 'Restaurant')
QT_TRANSLATE_NOOP('Mem', 'Transfer. Origin')
QT_TRANSLATE_NOOP('Mem', 'Transfer. Destination')
QT_TRANSLATE_NOOP('Mem', 'Taxes. Returned')
QT_TRANSLATE_NOOP('Mem', 'Gasoline')
QT_TRANSLATE_NOOP('Mem', 'Leisure')
QT_TRANSLATE_NOOP('Mem', 'Teléfono')
QT_TRANSLATE_NOOP('Mem', 'Paysheet')
QT_TRANSLATE_NOOP('Mem', 'Televisión & Video & Cine')
QT_TRANSLATE_NOOP('Mem', 'Casa. Comunidad')
QT_TRANSLATE_NOOP('Mem', 'Universidad & Estudios')
QT_TRANSLATE_NOOP('Mem', 'Viajes (Billetes y autopistas)')
QT_TRANSLATE_NOOP('Mem', 'Hoteles')
QT_TRANSLATE_NOOP('Mem', 'Loterías')
QT_TRANSLATE_NOOP('Mem', 'Regalos')
QT_TRANSLATE_NOOP('Mem', 'Electricidad')
QT_TRANSLATE_NOOP('Mem', 'Gas')
QT_TRANSLATE_NOOP('Mem', 'Intereses Negativos')
QT_TRANSLATE_NOOP('Mem', 'Ropa')
QT_TRANSLATE_NOOP('Mem', 'Médicos ')
QT_TRANSLATE_NOOP('Mem', 'Intereses Positivos')
QT_TRANSLATE_NOOP('Mem', 'Loterías Premios')
QT_TRANSLATE_NOOP('Mem', 'Informática')
QT_TRANSLATE_NOOP('Mem', 'Coche')
QT_TRANSLATE_NOOP('Mem', 'Herencia')
QT_TRANSLATE_NOOP('Mem', 'Purchase investment product')
QT_TRANSLATE_NOOP('Mem', 'Pagas')
QT_TRANSLATE_NOOP('Mem', 'Invitaciones')
QT_TRANSLATE_NOOP('Mem', 'Otros Ingresos')
QT_TRANSLATE_NOOP('Mem', 'Casa. Compra')
QT_TRANSLATE_NOOP('Mem', 'Sale investment product')
QT_TRANSLATE_NOOP('Mem', 'Casa. Infraestructura')
QT_TRANSLATE_NOOP('Mem', 'Taxes. Paid')
QT_TRANSLATE_NOOP('Mem', 'Bank commissions')
QT_TRANSLATE_NOOP('Mem', 'Dividends')
QT_TRANSLATE_NOOP('Mem', 'Credit card billing')
QT_TRANSLATE_NOOP('Mem', 'Added shares')
QT_TRANSLATE_NOOP('Mem', 'Ajustes negativos')
QT_TRANSLATE_NOOP('Mem', 'Casa. Compra pareja')
QT_TRANSLATE_NOOP('Mem', 'Préstamo (Me devuelven)')
QT_TRANSLATE_NOOP('Mem', 'Seguro')
QT_TRANSLATE_NOOP('Mem', 'Boda')
QT_TRANSLATE_NOOP('Mem', 'Regalos económicos recibidos')
QT_TRANSLATE_NOOP('Mem', 'Attendance bonus')
QT_TRANSLATE_NOOP('Mem', 'Otros Ingresos Pareja')
QT_TRANSLATE_NOOP('Mem', 'Casa. Asistenta')
QT_TRANSLATE_NOOP('Mem', 'Taxi')
QT_TRANSLATE_NOOP('Mem', 'Copas')
QT_TRANSLATE_NOOP('Mem', 'Gimnasio')
QT_TRANSLATE_NOOP('Mem', 'Divorcio')
QT_TRANSLATE_NOOP('Mem', 'Donaciones')
QT_TRANSLATE_NOOP('Mem', 'Garage')
QT_TRANSLATE_NOOP('Mem', 'Custody commission')
QT_TRANSLATE_NOOP('Mem', 'Casa. Alquiler')
QT_TRANSLATE_NOOP('Mem', 'Dividends. Sale of rights')
QT_TRANSLATE_NOOP('Mem', 'Bonds. Running coupon payment')
QT_TRANSLATE_NOOP('Mem', 'Pareja. Apoyo')
QT_TRANSLATE_NOOP('Mem', 'Bonds. Running coupon collection')
QT_TRANSLATE_NOOP('Mem', 'Bonds. Coupon collection')
QT_TRANSLATE_NOOP('Mem', 'Credit card refund')
QT_TRANSLATE_NOOP('Mem', 'Derivatives. Daily adjustment')
QT_TRANSLATE_NOOP('Mem', 'Derivatives. Daily guarantee')
QT_TRANSLATE_NOOP('Mem', 'Derivatives. Operation commission')
QT_TRANSLATE_NOOP('Mem', 'Rollover Paid')
QT_TRANSLATE_NOOP('Mem', 'Rollover Received')
