# -*- coding: UTF-8 -*-
from mod_python import util
from core import *
from xul import *

def index(req):
    form=req.form
    if form.has_key('id_inversiones'):
       id_inversiones=int(form['id_inversiones'])
    else:
        util.redirect(req, 'inversion_informacion.py')
        
    con=Conection()
    cmbtiposoperaciones=TipoOperacion().cmb('select * from tiposoperaciones where operinversion=true order by tipooperacion',  4,  False)
    
    req.content_type="application/vnd.mozilla.xul+xml"
    req.write(xulheaderwindowmenu("Insertando una operación de inversiones"))
    con.close()


    req.write('<script src="js/validar.js"></script>\n')
    req.write('<script>\n')
    req.write('<![CDATA[\n')
    req.write('function insert(){\n')
    req.write('    if (isISODate(document.getElementById("fecha").value,"La fecha no es válida")==false ||\n')
    req.write('        isFloat(document.getElementById("importe").value,"El importe no es un decimal")==false ||\n')
    req.write('        isFloat(document.getElementById("acciones").value,"El número de acciones no es un decimal")==false ||\n')
    req.write('        isFloat(document.getElementById("impuestos").value,"El campo de impuestos no es un decimal")==false ||\n')
    req.write('        isFloat(document.getElementById("comision").value,"La comision no es un decimal")==false ||\n')
    req.write('        isFloat(document.getElementById("valor_accion").value,"El valor de la acción no es un decimal")==false\n')
    req.write('        ){\n')
    req.write('        return;\n')
    req.write('    }\n')
    req.write('    if (document.getElementById("acciones").value==0 ){\n')
    req.write('        alert("El número de acciones no puede ser 0");\n')
    req.write('        return;\n')
    req.write('    }\n')

    req.write('    var xmlHttp;    \n')
    req.write('    var id_tiposoperaciones=document.getElementById("cmbtiposoperaciones").value\n')
    req.write('    var importe=document.getElementById("importe").value;\n')
    req.write('    var fecha = document.getElementById("fecha").value;\n')
    req.write('    var acciones = document.getElementById("acciones").value;\n')
    req.write('    var impuestos = document.getElementById("impuestos").value;\n')
    req.write('    var comision = document.getElementById("comision").value;\n')
    req.write('    var valor_accion = document.getElementById("valor_accion").value;\n')
    req.write('    spfecha=fecha.split("-");\n')
    req.write('    var id_inversiones='+str(id_inversiones)+';\n')
    req.write('    var url="ajax/inversionoperacion_insertar.py?fecha="+fecha+"&id_tiposoperaciones="+id_tiposoperaciones+"&importe="+importe+"&acciones="+acciones+"&impuestos="+impuestos+"&comision="+comision+"&valor_accion="+valor_accion+"&id_inversiones="+id_inversiones;\n')
    req.write('    xmlHttp=new XMLHttpRequest();\n')
    req.write('    xmlHttp.onreadystatechange=function(){\n')
    req.write('        if(xmlHttp.readyState==4){\n')
    req.write('            var ale=xmlHttp.responseText;\n')
    req.write('            parse_ale(ale,"inversionoperacion_listado.py?id_inversiones="+ id_inversiones )\n')
    req.write('        }\n')
    req.write('    }\n')

    req.write('    xmlHttp.open("GET",url,true);\n')
    req.write('    xmlHttp.send(null);\n')
    req.write('}\n')
    req.write(']]>\n')
    req.write('</script>\n')
    req.write('<label id="titulo" value="Nueva operación de inversiones" />\n')
    req.write('<vbox flex="5">\n')
    req.write('<grid pack="center">\n')
    req.write('    <columns>\n')
    req.write('        <column flex="1" />\n')
    req.write('        <column flex="1" />\n')
    req.write('    </columns>\n')
    req.write('    <rows>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Fecha"/>\n')
    req.write('            <datepicker id="fecha" type="grid"  firstdayofweek="1"/>\n')
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Tipo de operación"/>\n')
    req.write(cmbtiposoperaciones)
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Importe"/>\n')
    req.write('            <textbox id="importe" value="0"/>\n')
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Acciones"/>\n')
    req.write('            <textbox id="acciones" value="0"/>\n')
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Impuestos"/>\n')
    req.write('            <textbox id="impuestos" value="0"/>\n')
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Comisión"/>\n')
    req.write('            <textbox id="comision" value="0"/>\n')
    req.write('        </row>\n')
    req.write('        <row>\n')
    req.write('            <label id="negrita" value="Valor de la acción"/>\n')
    req.write('            <textbox id="valor_accion" value="0"/>\n')
    req.write('        </row>\n')
    req.write('    </rows>\n')
    req.write('</grid>\n')
    req.write('    <button label="Aceptar" oncommand="insert();"/>\n')

    req.write('</vbox>\n')
    req.write('</window>\n')
